### ISSUE TITLE
[Bug] Toggles with multiple options Disappear before Clickable

### ISSUE THREAD

**Issue by ChasarooniZ** [Saibot393/enhancedcombathud-vaesen#1]
Toggles with multiple options seem to disappear before I can choose another option

**Comment by Saibot393** [comment]
I will look into it

**Comment by Saibot393** [comment]
Which browser are you using? The Foundry Lightweight Client?

**Comment by ChasarooniZ** [comment]
MS Edge

**Comment by Saibot393** [comment]
Should now be fixed with v1.2.0
