### ISSUE TITLE
[Feature] Weapon Toggle Visibility

### ISSUE THREAD

**Issue by ChasarooniZ** [Saibot393/enhancedcombathud-vaesen#2]
For weapon toggles and the toggles with multiple options, some CSS to make them standout better against the background may help with usability

**Comment by Saibot393** [comment]
The weapon toggle icons can already be scaled up and a background shadow can be set, my css skills are honestly too limited to add much more. I will look into the toggle selects though

**Comment by ChasarooniZ** [comment]
Okay that works too, thanks, was unsure what the settings meant but that makes sense.
