### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by Dolgrenn** [Saibot393/enhancedcombathud-vaesen#3]
First of all, thank you for the wonderful work you've done for the Vaesen community on Foundry. Is a French translation possible?

I can help if I need to.

Thanks in advance.

**Comment by Saibot393** [comment]
Happy to hear that you like the module.

If you want to make a french translation here is how that would work:

1. Download one of the available language .json files for the module (probably the [english one](https://github.com/Saibot393/enhancedcombathud-vaesen/blob/main/lang/en.json))
2. (optional) download an appropiate programm to edit .json files, the normal text editor should work but something like notepad++ is nice for things like highlighting
3. In the file, replace the text on the right side (red in the screenshot) with the appropiate french translation (the blue/purple text to the left contains the keys for the module to find the translation texts). Make sure to keep text in curly brackets unchanged as they will later be replaced by specific values, you can however freely move them around in the text. Note that to write `"` yo have to write `\"`.
4. Once you are done (completely or in parts), you can upload the new translation file here, i will then add it to the module

![image](https://github.com/Saibot393/enhancedcombathud-vaesen/assets/137942782/e5e21f96-d292-4f7a-99f8-9accdff40f3d)


I would be quite grateful for any translation work done. Feel free to ask should any further questions come up.

**Comment by Dolgrenn** [comment]
[en.json](https://github.com/user-attachments/files/15977314/en.json)

Thank you for your very thorough explanations. I've done a quick initial translation of the entire .json

**Comment by Dolgrenn** [comment]
Thank you for your very thorough explanations. I've done a quick initial translation of the entire .json
[fr.json](https://github.com/user-attachments/files/15977584/fr.json)

**Comment by Saibot393** [comment]
Thank you very much, i have added your french translation with v2.0.1
